name: Steam Workshop Download

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  steam-workshop-download:
    runs-on: ubuntu-latest
    steps:
      - name: Check Steam Workshop item updates
        run: |
          curl -X POST https://api.steampowered.com/ISteamRemoteStorage/GetPublishedFileDetails/v1/ \
            -H "Content-Type: application/x-www-form-urlencoded" \
            -d "itemcount=1" \
            -d "publishedfileids[0]=${{ vars.WORKSHOP_ITEM_ID }}" \
            | jq '.response.publishedfiledetails[0].time_updated'
      - name: Install SteamCMD
        uses: andriivitiv/setup-steamcmd@v1.2.0
      - name: Install fastgmad
        run: |   
          curl -LO https://github.com/WilliamVenner/fastgmad/releases/latest/download/fastgmad_linux.zip
          unzip fastgmad_linux.zip
          chmod +x fastgmad
          sudo mv fastgmad /usr/local/bin
      - name: Download Steam Workshop item
        id: download
        run: |
          steamcmd +login anonymous +workshop_download_item 4000 ${{ vars.WORKSHOP_ITEM_ID }} +quit
          GMA=$(find ~/Steam/steamapps/workshop/content/4000/${{ vars.WORKSHOP_ITEM_ID }} -name "*.gma" | head -n 1)
          echo "GMA=$GMA" >> $GITHUB_OUTPUT
      - name: Extract GMA
        run: |
          pwd; ls
          fastgmad extract -file ${{ steps.download.outputs.GMA }} -out ${{ runner.temp }}
      - name: Checkout repository
        uses: actions/checkout@v7.0.0
      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Commit and push
        run: |
          cp -r ${{ runner.temp }} ./
          git commit -am "Updated from Workshop"
          git push origin main
